services:
  client_cache_proxy:
    image: todo-frontend
    ports:
      - 8080:80
    container_name: todo-frontend
    depends_on:
      - server

  server:
    image: todo-backend
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-backend
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_prod:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data_prod:/data

# Store prod data in different Docker-controlled file to dev data
volumes:
  mongo_data_prod:
  redis_data_prod:
